"""Added password field

Revision ID: 75fe105914eb
Revises: 
Create Date: 2022-05-16 08:05:46.136149

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '75fe105914eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
