"""Removed password field

Revision ID: d79ddb3a75f1
Revises: 75fe105914eb
Create Date: 2022-05-23 16:38:27.312240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79ddb3a75f1'
down_revision = '75fe105914eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
